import {Metadata} from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = { children: React.ReactNode };

const  postsLayout =({children}: Props)=>{


  return (
<>
    {children}
</>
  );
}
export default postsLayout;