import {Metadata} from "next";

export const metadata: Metadata = {
  title: "Cars page",
  description: "Generated by create next app",
};

type Props = { children: React.ReactNode };

const  carsPage =({children}: Props)=>{


  return (
<>
    {children}
</>
  );
}
export default carsPage;